blueprint:
- Nested VCF Modular - Foundation
- Nested VCF Modular - ESXi
- Nested VCF Modular - Installer
- Nested VCF Modular - Jumphost
property-group: []
custom-resource:
- VCF
- VCF Installler Certificate
resource-action: []
workflow: []
subscription: []
policy:
  approval: []
  day2-actions: []
  iaas-resource: []
  lease: []
scenario: []
